import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'

const Layout = ({children}) => {
  return (
    <div className='layout'>
      <Head>
        <title>Эполет</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ep.png" />
      </Head>
      <header className='navbar'>
        <Navbar />
      </header>
      <main className='mainn'>
        {children}
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}

export default Layout